import {
  BookingStatus,
  PaymentStatus,
  VehicleType,
  CancellationReason,
  NotificationType,
  DocumentStatus,
  SupportStatus,
  UserRole,
  TripType,
  DiscountType,
  SortingType,
  DriverStatus,
  type Driver,
  type Operator,
  type Passenger,
  type Vehicle,
  type Booking,
  type Quote,
  type Review,
  type PricingRule,
  type Location,
  type SavedLocation,
  type DriverAvailability,
} from '../types';

export const BRAND = {
  name: 'Blue Star Airport Transfers LTD',
  tagline: 'Your Journey, Your Way',
  description:
    'Blue Star Airport Transfers LTD is a premium taxi booking platform connecting passengers with licensed taxi operators across the United Kingdom. Compare quotes, track your ride, and travel with confidence.',
} as const;

export const DEFAULT_ADMIN = {
  email: 'admin@bstcars.co',
  password: 'Admin@123',
  firstName: 'Admin',
  lastName: 'User',
  phone: '+442071234567',
  role: 'admin' as const,
} as const;

export const COLORS = {
  primary: '#1E3A5F',
  primaryLight: '#2E5A8F',
  primaryDark: '#0F1F35',
  secondary: '#D4AF37',
  secondaryLight: '#E5C76B',
  secondaryDark: '#B8941E',
  accent: '#27AE60',
  accentLight: '#2ECC71',
  accentDark: '#1E8449',
  background: '#F8F9FA',
  surface: '#FFFFFF',
  surfaceElevated: '#F0F2F5',
  text: '#1A1A2E',
  textSecondary: '#6C757D',
  textMuted: '#ADB5BD',
  textInverse: '#FFFFFF',
  border: '#DEE2E6',
  borderLight: '#E9ECEF',
  error: '#DC3545',
  errorLight: '#F8D7DA',
  errorDark: '#C82333',
  warning: '#FFC107',
  warningLight: '#FFF3CD',
  warningDark: '#E0A800',
  success: '#28A745',
  successLight: '#D4EDDA',
  successDark: '#1E7E34',
  info: '#17A2B8',
  infoLight: '#D1ECF1',
  infoDark: '#117A8B',
  overlay: 'rgba(0, 0, 0, 0.5)',
  shadow: 'rgba(0, 0, 0, 0.1)',
  electric: '#00B4D8',
  hybrid: '#48CAE4',
  executive: '#C9B037',
} as const;

export const UK_AIRPORTS = [
  {
    code: 'LHR',
    name: 'London Heathrow Airport',
    city: 'London',
    location: { latitude: 51.47, longitude: -0.4543 },
    postcode: 'TW6',
  },
  {
    code: 'LGW',
    name: 'London Gatwick Airport',
    city: 'London',
    location: { latitude: 51.1537, longitude: -0.1821 },
    postcode: 'RH6',
  },
  {
    code: 'STN',
    name: 'London Stansted Airport',
    city: 'London',
    location: { latitude: 51.885, longitude: 0.235 },
    postcode: 'CM24',
  },
  {
    code: 'LTN',
    name: 'London Luton Airport',
    city: 'London',
    location: { latitude: 51.8747, longitude: -0.3683 },
    postcode: 'LU2',
  },
  {
    code: 'LCY',
    name: 'London City Airport',
    city: 'London',
    location: { latitude: 51.5053, longitude: 0.0553 },
    postcode: 'E16',
  },
  {
    code: 'MAN',
    name: 'Manchester Airport',
    city: 'Manchester',
    location: { latitude: 53.4794, longitude: -2.2453 },
    postcode: 'M90',
  },
  {
    code: 'BHX',
    name: 'Birmingham Airport',
    city: 'Birmingham',
    location: { latitude: 52.4539, longitude: -1.748 },
    postcode: 'B26',
  },
  {
    code: 'EDI',
    name: 'Edinburgh Airport',
    city: 'Edinburgh',
    location: { latitude: 55.95, longitude: -3.3725 },
    postcode: 'EH12',
  },
  {
    code: 'GLA',
    name: 'Glasgow Airport',
    city: 'Glasgow',
    location: { latitude: 55.8719, longitude: -4.4331 },
    postcode: 'PA3',
  },
  {
    code: 'LPL',
    name: 'Liverpool John Lennon Airport',
    city: 'Liverpool',
    location: { latitude: 53.3336, longitude: -2.8497 },
    postcode: 'L24',
  },
  {
    code: 'BRS',
    name: 'Bristol Airport',
    city: 'Bristol',
    location: { latitude: 51.3827, longitude: -2.7191 },
    postcode: 'BS48',
  },
] as const;

export const UK_CITIES = [
  { name: 'London', postcode: 'EC1A', population: 8982000 },
  { name: 'Manchester', postcode: 'M1', population: 553000 },
  { name: 'Birmingham', postcode: 'B1', population: 1141000 },
  { name: 'Leeds', postcode: 'LS1', population: 793000 },
  { name: 'Glasgow', postcode: 'G1', population: 635000 },
  { name: 'Edinburgh', postcode: 'EH1', population: 525000 },
  { name: 'Liverpool', postcode: 'L1', population: 498000 },
  { name: 'Bristol', postcode: 'BS1', population: 467000 },
  { name: 'Cardiff', postcode: 'CF10', population: 362000 },
  { name: 'Belfast', postcode: 'BT1', population: 343000 },
  { name: 'Newcastle', postcode: 'NE1', population: 302000 },
  { name: 'Sheffield', postcode: 'S1', population: 584000 },
  { name: 'Nottingham', postcode: 'NG1', population: 332000 },
  { name: 'Southampton', postcode: 'SO14', population: 253000 },
  { name: 'Derby', postcode: 'DE1', population: 256000 },
  { name: 'Brighton', postcode: 'BN1', population: 290000 },
  { name: 'Coventry', postcode: 'CV1', population: 371000 },
  { name: 'Hull', postcode: 'HU1', population: 260000 },
  { name: 'Bradford', postcode: 'BD1', population: 350000 },
  { name: 'Plymouth', postcode: 'PL1', population: 264000 },
] as const;

export const VEHICLE_TYPES: { value: VehicleType; label: string; icon: string; description: string; passengerCapacity: number; luggageCapacity: number }[] = [
  { value: 'saloon', label: 'Saloon', icon: '🚗', description: 'Standard sedan, comfortable for up to 3 passengers', passengerCapacity: 3, luggageCapacity: 2 },
  { value: 'executive', label: 'Executive', icon: '🏎️', description: 'Premium vehicle with luxury finish', passengerCapacity: 3, luggageCapacity: 2 },
  { value: 'estate', label: 'Estate', icon: '🚙', description: 'Spacious estate car with extra luggage space', passengerCapacity: 3, luggageCapacity: 4 },
  { value: 'mpv', label: 'MPV', icon: '🚐', description: 'Multi-purpose vehicle for groups and families', passengerCapacity: 6, luggageCapacity: 4 },
  { value: 'minibus', label: 'Minibus', icon: '🚌', description: 'Large vehicle for groups of up to 8 passengers', passengerCapacity: 8, luggageCapacity: 6 },
  { value: 'electric', label: 'Electric', icon: '⚡', description: 'Zero-emission electric vehicle', passengerCapacity: 3, luggageCapacity: 2 },
  { value: 'wheelchair_accessible', label: 'Wheelchair Accessible', icon: '♿', description: 'Fully adapted vehicle with wheelchair ramp', passengerCapacity: 2, luggageCapacity: 1 },
];

export const BOOKING_STATUSES: { value: BookingStatus; label: string; color: string }[] = [
  { value: BookingStatus.PendingPayment, label: 'Pending Payment', color: '#FFC107' },
  { value: BookingStatus.CashPendingApproval, label: 'Cash – Awaiting Approval', color: '#D97706' },
  { value: BookingStatus.PaymentFailed, label: 'Payment Failed', color: '#DC3545' },
  { value: BookingStatus.Confirmed, label: 'Confirmed', color: '#28A745' },
  { value: BookingStatus.OperatorPending, label: 'Operator Pending', color: '#6C757D' },
  { value: BookingStatus.DriverSearching, label: 'Driver Searching', color: '#17A2B8' },
  { value: BookingStatus.DriverAssigned, label: 'Driver Assigned', color: '#1E3A5F' },
  { value: BookingStatus.DriverAccepted, label: 'Driver Accepted', color: '#2E5A8F' },
  { value: BookingStatus.DriverEnRoute, label: 'Driver En Route', color: '#007BFF' },
  { value: BookingStatus.DriverArrived, label: 'Driver Arrived', color: '#D4AF37' },
  { value: BookingStatus.PassengerOnboard, label: 'Passenger Onboard', color: '#27AE60' },
  { value: BookingStatus.TripStarted, label: 'Trip Started', color: '#27AE60' },
  { value: BookingStatus.TripCompleted, label: 'Trip Completed', color: '#28A745' },
  { value: BookingStatus.CancelledByPassenger, label: 'Cancelled by Passenger', color: '#DC3545' },
  { value: BookingStatus.CancelledByDriver, label: 'Cancelled by Driver', color: '#DC3545' },
  { value: BookingStatus.CancelledByOperator, label: 'Cancelled by Operator', color: '#DC3545' },
  { value: BookingStatus.CancelledByAdmin, label: 'Cancelled by Admin', color: '#DC3545' },
  { value: BookingStatus.NoShow, label: 'No Show', color: '#6C757D' },
];

export const PAYMENT_STATUSES: { value: PaymentStatus; label: string; color: string }[] = [
  { value: 'pending', label: 'Pending', color: '#FFC107' },
  { value: 'processing', label: 'Processing', color: '#17A2B8' },
  { value: 'completed', label: 'Completed', color: '#28A745' },
  { value: 'failed', label: 'Failed', color: '#DC3545' },
  { value: 'refunded', label: 'Refunded', color: '#6C757D' },
  { value: 'partial_refund', label: 'Partial Refund', color: '#FFC107' },
];

export const DOCUMENT_TYPES = [
  'Driving Licence',
  'DVLA Check Code',
  'Insurance Certificate',
  'MOT Certificate',
  'Private Hire Licence',
  'PCO Licence',
  'PHV Licence',
  'DBS Check',
  'Right to Work',
  'Medical Certificate',
  'Topographical Assessment',
  'Vehicle Registration',
] as const;

export const CANCELLATION_REASONS: { value: CancellationReason; label: string }[] = [
  { value: CancellationReason.ChangedMind, label: 'Changed my mind' },
  { value: CancellationReason.FoundAlternative, label: 'Found an alternative' },
  { value: CancellationReason.TooExpensive, label: 'Too expensive' },
  { value: CancellationReason.NoShow, label: 'No show' },
  { value: CancellationReason.VehicleIssue, label: 'Vehicle issue' },
  { value: CancellationReason.DriverIssue, label: 'Driver issue' },
  { value: CancellationReason.Weather, label: 'Weather conditions' },
  { value: CancellationReason.PersonalEmergency, label: 'Personal emergency' },
  { value: CancellationReason.DuplicateBooking, label: 'Duplicate booking' },
  { value: CancellationReason.WrongDetails, label: 'Wrong booking details' },
  { value: CancellationReason.Other, label: 'Other' },
];

export const SUPPORT_CATEGORIES = [
  { id: 'booking', label: 'Booking Issue', description: 'Problems with a current or past booking' },
  { id: 'payment', label: 'Payment Issue', description: 'Payment failures, refunds, or billing questions' },
  { id: 'account', label: 'Account', description: 'Account access, profile, or settings' },
  { id: 'driver', label: 'Driver Issue', description: 'Report a driver or driver-related concern' },
  { id: 'vehicle', label: 'Vehicle Issue', description: 'Vehicle quality, cleanliness, or accessibility' },
  { id: 'lost_property', label: 'Lost Property', description: 'Items left in a vehicle' },
  { id: 'feedback', label: 'Feedback', description: 'General feedback or suggestions' },
  { id: 'safety', label: 'Safety Concern', description: 'Report a safety incident' },
  { id: 'promo_code', label: 'Promo Code', description: 'Issues with promotional codes' },
  { id: 'technical', label: 'Technical Issue', description: 'App or website problems' },
  { id: 'other', label: 'Other', description: 'Anything else' },
] as const;

export const PRICING_DEFAULTS = {
  baseFare: 3.5,
  perMile: 1.8,
  perMinute: 0.3,
  minimumFare: 5.0,
  bookingFee: 1.5,
  airportFee: 5.0,
  nightSurchargePercent: 20,
  weekendSurchargePercent: 10,
  peakTimeSurchargePercent: 25,
  congestionCharge: 15.0,
  taxRate: 20,
  cancellationFee: 5.0,
  waitingFeePerMinute: 0.5,
  freeWaitingMinutes: 5,
  maxWaitMinutes: 15,
} as const;

export const NAVIGATION = {
  main: [
    { id: 'home', label: 'Home', path: '/', icon: 'Home' },
    { id: 'book', label: 'Book a Ride', path: '/book', icon: 'Car' },
    { id: 'tracking', label: 'Live Tracking', path: '/tracking', icon: 'MapPin' },
    { id: 'history', label: 'My Trips', path: '/history', icon: 'Clock' },
    { id: 'help', label: 'Help', path: '/help', icon: 'HelpCircle' },
  ],
  passenger: [
    { id: 'dashboard', label: 'Dashboard', path: '/passenger/dashboard', icon: 'LayoutDashboard' },
    { id: 'book', label: 'Book Now', path: '/passenger/book', icon: 'Car' },
    { id: 'active', label: 'Active Trip', path: '/passenger/active', icon: 'Navigation' },
    { id: 'history', label: 'Trip History', path: '/passenger/history', icon: 'History' },
    { id: 'saved', label: 'Saved Places', path: '/passenger/saved', icon: 'Bookmark' },
    { id: 'payments', label: 'Payments', path: '/passenger/payments', icon: 'CreditCard' },
    { id: 'notifications', label: 'Notifications', path: '/passenger/notifications', icon: 'Bell' },
    { id: 'profile', label: 'Profile', path: '/passenger/profile', icon: 'User' },
  ],
  driver: [
    { id: 'dashboard', label: 'Dashboard', path: '/driver/dashboard', icon: 'LayoutDashboard' },
    { id: 'go_online', label: 'Go Online', path: '/driver/online', icon: 'Power' },
    { id: 'bookings', label: 'Bookings', path: '/driver/bookings', icon: 'ClipboardList' },
    { id: 'active', label: 'Active Trip', path: '/driver/active', icon: 'Navigation' },
    { id: 'earnings', label: 'Earnings', path: '/driver/earnings', icon: 'Wallet' },
    { id: 'documents', label: 'Documents', path: '/driver/documents', icon: 'FileText' },
    { id: 'vehicle', label: 'My Vehicle', path: '/driver/vehicle', icon: 'Car' },
    { id: 'notifications', label: 'Notifications', path: '/driver/notifications', icon: 'Bell' },
    { id: 'profile', label: 'Profile', path: '/driver/profile', icon: 'User' },
  ],
  operator: [
    { id: 'dashboard', label: 'Dashboard', path: '/operator/dashboard', icon: 'LayoutDashboard' },
    { id: 'bookings', label: 'All Bookings', path: '/operator/bookings', icon: 'ClipboardList' },
    { id: 'drivers', label: 'Drivers', path: '/operator/drivers', icon: 'Users' },
    { id: 'fleet', label: 'Fleet', path: '/operator/fleet', icon: 'Truck' },
    { id: 'pricing', label: 'Pricing', path: '/operator/pricing', icon: 'DollarSign' },
    { id: 'earnings', label: 'Earnings', path: '/operator/earnings', icon: 'Wallet' },
    { id: 'reviews', label: 'Reviews', path: '/operator/reviews', icon: 'Star' },
    { id: 'reports', label: 'Reports', path: '/operator/reports', icon: 'BarChart2' },
    { id: 'notifications', label: 'Notifications', path: '/operator/notifications', icon: 'Bell' },
    { id: 'settings', label: 'Settings', path: '/operator/settings', icon: 'Settings' },
  ],
  admin: [
    { id: 'dashboard', label: 'Dashboard', path: '/admin/dashboard', icon: 'LayoutDashboard' },
    { id: 'bookings', label: 'Bookings', path: '/admin/bookings', icon: 'ClipboardList' },
    { id: 'passengers', label: 'Passengers', path: '/admin/passengers', icon: 'Users' },
    { id: 'drivers', label: 'Drivers', path: '/admin/drivers', icon: 'Car' },
    { id: 'operators', label: 'Operators', path: '/admin/operators', icon: 'Building' },
    { id: 'payments', label: 'Payments', path: '/admin/payments', icon: 'CreditCard' },
    { id: 'documents', label: 'Documents', path: '/admin/documents', icon: 'FileText' },
    { id: 'promo_codes', label: 'Promo Codes', path: '/admin/promo-codes', icon: 'Tag' },
    { id: 'support', label: 'Support', path: '/admin/support', icon: 'Headphones' },
    { id: 'analytics', label: 'Analytics', path: '/admin/analytics', icon: 'BarChart2' },
    { id: 'audit_log', label: 'Audit Log', path: '/admin/audit-log', icon: 'Scroll' },
    { id: 'settings', label: 'Settings', path: '/admin/settings', icon: 'Settings' },
  ],
} as const;

export const UK_POSTCODE_REGEX = /^[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}$/i;

export const SERVICE_AREAS = [
  { name: 'Central London', postcodes: ['EC1', 'EC2', 'EC3', 'EC4', 'WC1', 'WC2', 'W1', 'SW1', 'SE1', 'N1', 'E1', 'NW1'] },
  { name: 'Greater London', postcodes: ['E', 'EN', 'HA', 'IG', 'KT', 'N', 'NW', 'RM', 'SE', 'SM', 'SW', 'TW', 'UB', 'W', 'WD'] },
  { name: 'Manchester', postcodes: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17', 'M18', 'M19', 'M20', 'M21', 'M22', 'M23', 'M24', 'M25', 'M26', 'M27', 'M28', 'M29', 'M30', 'M31', 'M32', 'M33', 'M34', 'M35', 'M40', 'M41', 'M43', 'M44', 'M45', 'M46', 'M60', 'M90'] },
  { name: 'Birmingham', postcodes: ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B10', 'B11', 'B12', 'B13', 'B14', 'B15', 'B16', 'B17', 'B18', 'B19', 'B20', 'B21', 'B23', 'B24', 'B25', 'B26', 'B27', 'B28', 'B29', 'B30', 'B31', 'B32', 'B33', 'B34', 'B35', 'B36', 'B37', 'B38', 'B40', 'B42', 'B43', 'B44', 'B45', 'B46', 'B47', 'B48', 'B49', 'B50', 'B62', 'B63', 'B64', 'B65', 'B66', 'B67', 'B68', 'B69', 'B70', 'B71', 'B72', 'B73', 'B74', 'B75', 'B76', 'B77', 'B78', 'B79'] },
  { name: 'Edinburgh', postcodes: ['EH1', 'EH2', 'EH3', 'EH4', 'EH5', 'EH6', 'EH7', 'EH8', 'EH9', 'EH10', 'EH11', 'EH12', 'EH13', 'EH14', 'EH15', 'EH16', 'EH17', 'EH18', 'EH19', 'EH20', 'EH21', 'EH22', 'EH23', 'EH24', 'EH25', 'EH26', 'EH27', 'EH28', 'EH29', 'EH30', 'EH31', 'EH32', 'EH33', 'EH34', 'EH35', 'EH36', 'EH37', 'EH38', 'EH39', 'EH40', 'EH41', 'EH42', 'EH43', 'EH44', 'EH45', 'EH46', 'EH47', 'EH48', 'EH49', 'EH51', 'EH52', 'EH53', 'EH54', 'EH55'] },
  { name: 'Glasgow', postcodes: ['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G11', 'G12', 'G13', 'G14', 'G15', 'G20', 'G21', 'G22', 'G23', 'G31', 'G32', 'G33', 'G34', 'G40', 'G41', 'G42', 'G43', 'G44', 'G45', 'G46', 'G51', 'G52', 'G53', 'G60', 'G61', 'G62', 'G63', 'G64', 'G65', 'G66', 'G67', 'G68', 'G69', 'G71', 'G72', 'G73', 'G74', 'G75', 'G76', 'G77', 'G78', 'G79', 'G81', 'G82', 'G83', 'G84'] },
  { name: 'Liverpool', postcodes: ['L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9', 'L10', 'L11', 'L12', 'L13', 'L14', 'L15', 'L16', 'L17', 'L18', 'L19', 'L20', 'L21', 'L22', 'L23', 'L24', 'L25', 'L26', 'L27', 'L28', 'L29', 'L30', 'L31', 'L32', 'L33', 'L34', 'L35', 'L36', 'L37', 'L38', 'L39', 'L40', 'L67', 'L68', 'L69', 'L70'] },
  { name: 'Leeds', postcodes: ['LS1', 'LS2', 'LS3', 'LS4', 'LS5', 'LS6', 'LS7', 'LS8', 'LS9', 'LS10', 'LS11', 'LS12', 'LS13', 'LS14', 'LS15', 'LS16', 'LS17', 'LS18', 'LS19', 'LS20', 'LS21', 'LS22', 'LS23', 'LS24', 'LS25', 'LS26', 'LS27', 'LS28', 'LS29', 'LS99'] },
  { name: 'Bristol', postcodes: ['BS1', 'BS2', 'BS3', 'BS4', 'BS5', 'BS6', 'BS7', 'BS8', 'BS9', 'BS10', 'BS11', 'BS13', 'BS14', 'BS15', 'BS16', 'BS20', 'BS21', 'BS22', 'BS23', 'BS24', 'BS25', 'BS26', 'BS27', 'BS28', 'BS29', 'BS30', 'BS31', 'BS32', 'BS34', 'BS35', 'BS36', 'BS37', 'BS38', 'BS39', 'BS40', 'BS41', 'BS48', 'BS49'] },
  { name: 'Newcastle', postcodes: ['NE1', 'NE2', 'NE3', 'NE4', 'NE5', 'NE6', 'NE7', 'NE12', 'NE13', 'NE15', 'NE16', 'NE17', 'NE18', 'NE19', 'NE20', 'NE21', 'NE22', 'NE23', 'NE24', 'NE25', 'NE26', 'NE27', 'NE28', 'NE29', 'NE30', 'NE31', 'NE32', 'NE33', 'NE34', 'NE35', 'NE36', 'NE37', 'NE38', 'NE39', 'NE40', 'NE41', 'NE42', 'NE43', 'NE44', 'NE45', 'NE46', 'NE47', 'NE48', 'NE49', 'NE61', 'NE62', 'NE63', 'NE64', 'NE65', 'NE66', 'NE67', 'NE68', 'NE69', 'NE70', 'NE71'] },
  { name: 'Sheffield', postcodes: ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13', 'S14', 'S17', 'S18', 'S20', 'S21', 'S25', 'S26', 'S32', 'S33', 'S35', 'S36', 'S40', 'S41', 'S42', 'S43', 'S44', 'S45', 'S49', 'S60', 'S61', 'S62', 'S63', 'S65', 'S66', 'S70', 'S71', 'S72', 'S73', 'S74', 'S75', 'S80', 'S81'] },
  { name: 'Cardiff', postcodes: ['CF10', 'CF11', 'CF14', 'CF15', 'CF23', 'CF24', 'CF3', 'CF5', 'CF61', 'CF62', 'CF63', 'CF64', 'CF71', 'CF72', 'CF81', 'CF82', 'CF83'] },
  { name: 'Belfast', postcodes: ['BT1', 'BT2', 'BT3', 'BT4', 'BT5', 'BT6', 'BT7', 'BT8', 'BT9', 'BT10', 'BT11', 'BT12', 'BT13', 'BT14', 'BT15', 'BT16', 'BT17'] },
  { name: 'Nottingham', postcodes: ['NG1', 'NG2', 'NG3', 'NG4', 'NG5', 'NG6', 'NG7', 'NG8', 'NG9', 'NG10', 'NG11', 'NG12', 'NG13', 'NG14', 'NG15', 'NG16', 'NG17', 'NG18', 'NG19', 'NG20', 'NG21', 'NG22', 'NG23', 'NG24', 'NG25', 'NG31', 'NG32', 'NG33', 'NG34'] },
] as const;

// --- DEMO DATA ---

const demoLocations: Location[] = [
  {
    formattedAddress: '10 Downing Street, Westminster, London SW1A 2AA',
    latitude: 51.5034,
    longitude: -0.1276,
    placeId: 'ChIJr4rGcGBEdkgR6G_KfPNHh-w',
    postcode: 'SW1A 2AA',
    city: 'London',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Heathrow Airport, Terminal 5, Longford, Hillingdon UB6 8JH',
    latitude: 51.47,
    longitude: -0.4543,
    placeId: 'ChIJgQi8ajYbdkgRfKJFGvnNbXA',
    postcode: 'UB6 8JH',
    city: 'London',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Manchester Airport, Manchester M90 1QX',
    latitude: 53.4794,
    longitude: -2.2453,
    placeId: 'ChIJDfUPEhUxeUgRF_Wm_eEpnkY',
    postcode: 'M90 1QX',
    city: 'Manchester',
    country: 'United Kingdom',
  },
  {
    formattedAddress: '1 Manchester Square, London W1U 3PH',
    latitude: 51.5141,
    longitude: -0.1535,
    placeId: 'ChIJW4gA4kMEdkgRL1Vi7QxBJxQ',
    postcode: 'W1U 3PH',
    city: 'London',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Waverley Station, Edinburgh EH1 1BZ',
    latitude: 55.9521,
    longitude: -3.189,
    placeId: 'ChIJn_CvFEfBh0gRUgox1CQNxlw',
    postcode: 'EH1 1BZ',
    city: 'Edinburgh',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Birmingham New Street, Birmingham B2 4QA',
    latitude: 52.4776,
    longitude: -1.9081,
    placeId: 'ChIJLQ8dKBfDcUgRGP0xSLcIh0M',
    postcode: 'B2 4QA',
    city: 'Birmingham',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Liverpool ONE, Liverpool L1 8JQ',
    latitude: 53.4026,
    longitude: -2.9913,
    placeId: 'ChIJvZYCbshPZ0gRnJgBKXVyXaY',
    postcode: 'L1 8JQ',
    city: 'Liverpool',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Cardiff Central Station, Cardiff CF10 1EP',
    latitude: 51.4736,
    longitude: -3.1717,
    placeId: 'ChIJNwkjGjh2b0gRxWfmJSdOBMo',
    postcode: 'CF10 1EP',
    city: 'Cardiff',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Bristol Temple Meads, Bristol BS1 6QF',
    latitude: 51.449,
    longitude: -2.5813,
    placeId: 'ChIJrWE1Rp5NcUgRJrMiYj5FTx8',
    postcode: 'BS1 6QF',
    city: 'Bristol',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'Glasgow Central Station, Glasgow G1 1AE',
    latitude: 55.8596,
    longitude: -4.2581,
    placeId: 'ChIJrWE1Rp5NcUgRJrMiYj5FTx9',
    postcode: 'G1 1AE',
    city: 'Glasgow',
    country: 'United Kingdom',
  },
  {
    formattedAddress: 'The O2 Arena, Peninsula Square, London SE10 0DX',
    latitude: 51.5031,
    longitude: 0.0032,
    placeId: 'ChIJaU01f8sEdkgRrvSjLwMqfKE',
    postcode: 'SE10 0DX',
    city: 'London',
    country: 'United Kingdom',
  },
  {
    formattedAddress: '221B Baker Street, Marylebone, London NW1 6XE',
    latitude: 51.5238,
    longitude: -0.1585,
    placeId: 'ChIJr4rGcGBEdkgR6G_KfPNHh-x',
    postcode: 'NW1 6XE',
    city: 'London',
    country: 'United Kingdom',
  },
];

const savedLocations: SavedLocation[] = [
  {
    id: 'sl-001',
    userId: 'pass-001',
    label: 'Home',
    location: demoLocations[11],
    icon: 'home',
  },
  {
    id: 'sl-002',
    userId: 'pass-001',
    label: 'Office',
    location: demoLocations[3],
    icon: 'briefcase',
  },
  {
    id: 'sl-003',
    userId: 'pass-001',
    label: 'Heathrow Airport',
    location: demoLocations[1],
    icon: 'plane',
  },
];

const driverAvailability: DriverAvailability = {
  monday: [{ start: '06:00', end: '22:00' }],
  tuesday: [{ start: '06:00', end: '22:00' }],
  wednesday: [{ start: '06:00', end: '22:00' }],
  thursday: [{ start: '06:00', end: '22:00' }],
  friday: [{ start: '06:00', end: '23:00' }],
  saturday: [{ start: '08:00', end: '23:00' }],
  sunday: [{ start: '08:00', end: '21:00' }],
};

export const DEMO_DATA = {
  passengers: [
    {
      uid: 'pass-001',
      role: 'passenger' as const,
      firstName: 'James',
      lastName: 'Wilson',
      email: 'james.wilson@example.com',
      phone: '+447700900100',
      photoURL: '/avatars/james-wilson.jpg',
      status: 'active',
      createdAt: '2025-01-15T10:30:00Z',
      updatedAt: '2026-08-20T14:15:00Z',
      lastLoginAt: '2026-08-25T08:45:00Z',
      defaultPickup: demoLocations[11],
      defaultDestination: demoLocations[3],
      savedLocations: savedLocations,
      preferences: {
        defaultVehicleType: 'saloon' as VehicleType,
        notifications: true,
        emailUpdates: true,
        defaultLuggage: 2,
        defaultPassengers: 1,
      },
    },
    {
      uid: 'pass-002',
      role: 'passenger' as const,
      firstName: 'Emma',
      lastName: 'Thompson',
      email: 'emma.thompson@example.com',
      phone: '+447700900200',
      photoURL: '/avatars/emma-thompson.jpg',
      status: 'active',
      createdAt: '2025-03-22T09:00:00Z',
      updatedAt: '2026-08-18T11:30:00Z',
      lastLoginAt: '2026-08-24T17:20:00Z',
      defaultPickup: demoLocations[4],
      savedLocations: [],
      preferences: {
        defaultVehicleType: 'executive' as VehicleType,
        notifications: true,
        emailUpdates: false,
        defaultLuggage: 1,
        defaultPassengers: 1,
      },
    },
    {
      uid: 'pass-003',
      role: 'passenger' as const,
      firstName: 'Raj',
      lastName: 'Patel',
      email: 'raj.patel@example.com',
      phone: '+447700900300',
      status: 'active',
      createdAt: '2025-06-10T14:00:00Z',
      updatedAt: '2026-08-15T10:00:00Z',
      lastLoginAt: '2026-08-25T07:10:00Z',
      savedLocations: [],
      preferences: {
        notifications: true,
        emailUpdates: true,
        defaultLuggage: 3,
        defaultPassengers: 2,
      },
    },
    {
      uid: 'pass-004',
      role: 'passenger' as const,
      firstName: 'Sophie',
      lastName: 'Clarkson',
      email: 'sophie.clarkson@example.com',
      phone: '+447700900400',
      photoURL: '/avatars/sophie-clarkson.jpg',
      status: 'active',
      createdAt: '2025-09-05T12:00:00Z',
      updatedAt: '2026-08-22T16:45:00Z',
      lastLoginAt: '2026-08-25T09:30:00Z',
      savedLocations: [],
      preferences: {
        defaultVehicleType: 'mpv' as VehicleType,
        notifications: true,
        emailUpdates: true,
        defaultLuggage: 4,
        defaultPassengers: 4,
      },
    },
    {
      uid: 'pass-005',
      role: 'passenger' as const,
      firstName: 'David',
      lastName: 'Morgan',
      email: 'david.morgan@example.com',
      phone: '+447700900500',
      status: 'active',
      createdAt: '2026-01-20T08:30:00Z',
      updatedAt: '2026-08-19T13:20:00Z',
      lastLoginAt: '2026-08-24T20:15:00Z',
      savedLocations: [],
      preferences: {
        defaultVehicleType: 'electric' as VehicleType,
        notifications: true,
        emailUpdates: false,
        defaultLuggage: 1,
        defaultPassengers: 1,
      },
    },
  ] as Passenger[],

  drivers: [
    {
      uid: 'drv-001',
      role: 'driver' as const,
      firstName: 'Mohammed',
      lastName: 'Hassan',
      email: 'mohammed.hassan@driver.uk',
      phone: '+447700901100',
      photoURL: '/avatars/mohammed-hassan.jpg',
      createdAt: '2024-06-15T10:00:00Z',
      updatedAt: '2026-08-25T08:00:00Z',
      lastLoginAt: '2026-08-25T08:00:00Z',
      operatorId: 'op-001',
      vehicleId: 'veh-001',
      status: 'online' as DriverStatus,
      rating: 4.9,
      totalReviews: 847,
      licenceNumber: 'MOH1234567890',
      documents: [],
      lastLocation: { latitude: 51.5074, longitude: -0.1278, updatedAt: '2026-08-25T08:45:00Z' },
      isVerified: true,
      availability: driverAvailability,
    },
    {
      uid: 'drv-002',
      role: 'driver' as const,
      firstName: 'Sarah',
      lastName: 'O\'Brien',
      email: 'sarah.obrien@driver.uk',
      phone: '+447700901200',
      photoURL: '/avatars/sarah-obrien.jpg',
      createdAt: '2024-08-20T14:00:00Z',
      updatedAt: '2026-08-24T19:30:00Z',
      lastLoginAt: '2026-08-24T19:30:00Z',
      operatorId: 'op-001',
      vehicleId: 'veh-002',
      status: 'online' as DriverStatus,
      rating: 4.8,
      totalReviews: 623,
      licenceNumber: 'SAR9876543210',
      documents: [],
      lastLocation: { latitude: 51.5139, longitude: -0.1431, updatedAt: '2026-08-25T07:50:00Z' },
      isVerified: true,
      availability: driverAvailability,
    },
    {
      uid: 'drv-003',
      role: 'driver' as const,
      firstName: 'Amit',
      lastName: 'Sharma',
      email: 'amit.sharma@driver.uk',
      phone: '+447700901300',
      photoURL: '/avatars/amit-sharma.jpg',
      createdAt: '2025-01-10T09:00:00Z',
      updatedAt: '2026-08-25T07:45:00Z',
      lastLoginAt: '2026-08-25T07:45:00Z',
      operatorId: 'op-002',
      vehicleId: 'veh-003',
      status: 'busy' as DriverStatus,
      rating: 4.7,
      totalReviews: 312,
      licenceNumber: 'AMI4567890123',
      documents: [],
      lastLocation: { latitude: 53.4794, longitude: -2.2453, updatedAt: '2026-08-25T08:40:00Z' },
      isVerified: true,
      availability: driverAvailability,
    },
    {
      uid: 'drv-004',
      role: 'driver' as const,
      firstName: 'Peter',
      lastName: 'Davies',
      email: 'peter.davies@driver.uk',
      phone: '+447700901400',
      photoURL: '/avatars/peter-davies.jpg',
      createdAt: '2025-04-05T11:00:00Z',
      updatedAt: '2026-08-23T15:00:00Z',
      lastLoginAt: '2026-08-23T15:00:00Z',
      operatorId: 'op-002',
      vehicleId: 'veh-004',
      status: 'offline' as DriverStatus,
      rating: 4.6,
      totalReviews: 189,
      licenceNumber: 'PET7890123456',
      documents: [],
      lastLocation: { latitude: 52.4862, longitude: -1.8904, updatedAt: '2026-08-23T15:00:00Z' },
      isVerified: true,
      availability: driverAvailability,
    },
    {
      uid: 'drv-005',
      role: 'driver' as const,
      firstName: 'Linda',
      lastName: 'Nguyen',
      email: 'linda.nguyen@driver.uk',
      phone: '+447700901500',
      photoURL: '/avatars/linda-nguyen.jpg',
      createdAt: '2025-07-12T16:00:00Z',
      updatedAt: '2026-08-25T06:30:00Z',
      lastLoginAt: '2026-08-25T06:30:00Z',
      operatorId: 'op-003',
      vehicleId: 'veh-005',
      status: 'online' as DriverStatus,
      rating: 4.9,
      totalReviews: 456,
      licenceNumber: 'LIN3210987654',
      documents: [],
      lastLocation: { latitude: 55.9533, longitude: -3.1883, updatedAt: '2026-08-25T08:42:00Z' },
      isVerified: true,
      availability: driverAvailability,
    },
  ] as Driver[],

  operators: [
    {
      uid: 'op-001',
      role: 'operator' as const,
      firstName: 'Richard',
      lastName: 'Kingsley',
      email: 'richard@kingsleytravel.co.uk',
      phone: '+442071234567',
      photoURL: '/avatars/richard-kingsley.jpg',
      status: 'active',
      createdAt: '2023-03-01T10:00:00Z',
      updatedAt: '2026-08-20T12:00:00Z',
      lastLoginAt: '2026-08-25T07:30:00Z',
      companyName: 'Kingsley Travel',
      companyLogo: '/logos/kingsley-travel.png',
      description: 'Premium taxi operator serving Central and Greater London with a fleet of saloon and executive vehicles.',
      rating: 4.8,
      totalReviews: 3245,
      fleetSize: 45,
      isVerified: true,
      commission: { percent: 15, flatFee: 0.5 },
    },
    {
      uid: 'op-002',
      role: 'operator' as const,
      firstName: 'Fiona',
      lastName: 'McGregor',
      email: 'fiona@northerntaxi.co.uk',
      phone: '+441619876543',
      photoURL: '/avatars/fiona-mcgregor.jpg',
      status: 'active',
      createdAt: '2023-06-15T14:00:00Z',
      updatedAt: '2026-08-18T09:30:00Z',
      lastLoginAt: '2026-08-24T18:00:00Z',
      companyName: 'Northern Taxi Services',
      companyLogo: '/logos/northern-taxi.png',
      description: 'Reliable taxi services across Manchester and the North West, specialising in airport transfers.',
      rating: 4.6,
      totalReviews: 1890,
      fleetSize: 32,
      isVerified: true,
      commission: { percent: 18, flatFee: 0.25 },
    },
    {
      uid: 'op-003',
      role: 'operator' as const,
      firstName: 'Ewan',
      lastName: 'Campbell',
      email: 'ewan@capitaltaxis.edinburgh.co.uk',
      phone: '+441315551234',
      photoURL: '/avatars/ewan-campbell.jpg',
      status: 'active',
      createdAt: '2024-01-10T09:00:00Z',
      updatedAt: '2026-08-22T11:00:00Z',
      lastLoginAt: '2026-08-25T06:00:00Z',
      companyName: 'Capital Taxis Edinburgh',
      companyLogo: '/logos/capital-taxis.png',
      description: 'Edinburgh\'s trusted taxi operator, providing wheelchair accessible and standard vehicles across the city.',
      rating: 4.7,
      totalReviews: 987,
      fleetSize: 22,
      isVerified: true,
      commission: { percent: 12, flatFee: 0.75 },
    },
  ] as Operator[],

  vehicles: [
    {
      id: 'veh-001',
      operatorId: 'op-001',
      driverId: 'drv-001',
      make: 'Toyota',
      model: 'Prius',
      year: 2024,
      registration: 'LN24 TCO',
      colour: 'White',
      vehicleType: 'electric' as VehicleType,
      passengerCapacity: 3,
      luggageCapacity: 2,
      wheelchairAccessible: false,
      isElectric: true,
      isHybrid: true,
      photoURL: '/vehicles/toyota-prius-2024.jpg',
      isApproved: true,
      availabilityStatus: 'available',
    },
    {
      id: 'veh-002',
      operatorId: 'op-001',
      driverId: 'drv-002',
      make: 'Mercedes-Benz',
      model: 'E-Class',
      year: 2023,
      registration: 'LN23 MBC',
      colour: 'Black',
      vehicleType: 'executive' as VehicleType,
      passengerCapacity: 3,
      luggageCapacity: 2,
      wheelchairAccessible: false,
      isElectric: false,
      isHybrid: false,
      photoURL: '/vehicles/mercedes-eclass-2023.jpg',
      isApproved: true,
      availabilityStatus: 'in_use',
    },
    {
      id: 'veh-003',
      operatorId: 'op-002',
      driverId: 'drv-003',
      make: 'Ford',
      model: 'Mondeo Estate',
      year: 2024,
      registration: 'MN24 FME',
      colour: 'Silver',
      vehicleType: 'estate' as VehicleType,
      passengerCapacity: 3,
      luggageCapacity: 4,
      wheelchairAccessible: false,
      isElectric: false,
      isHybrid: true,
      photoURL: '/vehicles/ford-mondeo-2024.jpg',
      isApproved: true,
      availabilityStatus: 'available',
    },
    {
      id: 'veh-004',
      operatorId: 'op-002',
      driverId: 'drv-004',
      make: 'Volkswagen',
      model: 'Touran',
      year: 2023,
      registration: 'BM23 VWT',
      colour: 'Grey',
      vehicleType: 'mpv' as VehicleType,
      passengerCapacity: 6,
      luggageCapacity: 4,
      wheelchairAccessible: false,
      isElectric: false,
      isHybrid: false,
      photoURL: '/vehicles/vw-touran-2023.jpg',
      isApproved: true,
      availabilityStatus: 'out_of_service',
      availabilityNote: 'Scheduled service — back Monday',
    },
    {
      id: 'veh-005',
      operatorId: 'op-003',
      driverId: 'drv-005',
      make: 'Citroen',
      model: 'Berlingo',
      year: 2024,
      registration: 'ED24 CBL',
      colour: 'Blue',
      vehicleType: 'wheelchair_accessible' as VehicleType,
      passengerCapacity: 2,
      luggageCapacity: 1,
      wheelchairAccessible: true,
      isElectric: false,
      isHybrid: false,
      photoURL: '/vehicles/citroen-berlingo-2024.jpg',
      isApproved: true,
      availabilityStatus: 'available',
    },
    {
      id: 'veh-006',
      operatorId: 'op-001',
      driverId: 'drv-001',
      make: 'Hyundai',
      model: 'Ioniq 5',
      year: 2025,
      registration: 'LN25 HYE',
      colour: 'Titan Grey',
      vehicleType: 'electric' as VehicleType,
      passengerCapacity: 3,
      luggageCapacity: 2,
      wheelchairAccessible: false,
      isElectric: true,
      isHybrid: false,
      photoURL: '/vehicles/hyundai-ioniq5-2025.jpg',
      isApproved: true,
      availabilityStatus: 'available',
    },
  ] as Vehicle[],

  bookings: [
    {
      bookingNumber: 'UKTB-2026-000001',
      passengerId: 'pass-001',
      operatorId: 'op-001',
      driverId: 'drv-001',
      vehicleId: 'veh-001',
      tripType: 'one_way' as TripType,
      pickup: demoLocations[11],
      destination: demoLocations[1],
      viaStops: [],
      date: '2026-08-26',
      pickupTime: '06:30',
      passengers: 1,
      luggage: 2,
      specialRequirements: {
        childSeat: false,
        wheelchairAccessible: false,
        meetAndGreet: true,
        flightNumber: 'BA117',
        flightTracking: 'enabled',
        terminal: 'Terminal 5',
      },
      vehicleType: 'executive' as VehicleType,
      distanceMiles: 18.4,
      estimatedDuration: 45,
      price: 42.5,
      discount: 0,
      tax: 8.5,
      total: 51.0,
      currency: 'GBP',
      paymentStatus: 'completed' as PaymentStatus,
      bookingStatus: BookingStatus.TripCompleted,
      createdAt: '2026-08-20T14:30:00Z',
      updatedAt: '2026-08-26T07:30:00Z',
    },
    {
      bookingNumber: 'UKTB-2026-000002',
      passengerId: 'pass-002',
      operatorId: 'op-001',
      driverId: 'drv-002',
      vehicleId: 'veh-002',
      tripType: 'one_way' as TripType,
      pickup: demoLocations[3],
      destination: demoLocations[0],
      viaStops: [{ location: demoLocations[11], label: 'Quick Stop' }],
      date: '2026-08-25',
      pickupTime: '14:00',
      passengers: 2,
      luggage: 1,
      specialRequirements: {
        childSeat: false,
        wheelchairAccessible: false,
        meetAndGreet: false,
      },
      vehicleType: 'executive' as VehicleType,
      distanceMiles: 2.3,
      estimatedDuration: 15,
      price: 12.0,
      discount: 2.4,
      tax: 1.92,
      total: 11.52,
      currency: 'GBP',
      paymentStatus: 'completed' as PaymentStatus,
      bookingStatus: BookingStatus.DriverEnRoute,
      createdAt: '2026-08-24T16:00:00Z',
      updatedAt: '2026-08-25T13:50:00Z',
    },
    {
      bookingNumber: 'UKTB-2026-000003',
      passengerId: 'pass-003',
      operatorId: 'op-002',
      driverId: 'drv-003',
      vehicleId: 'veh-003',
      tripType: 'return' as TripType,
      pickup: demoLocations[5],
      destination: demoLocations[2],
      viaStops: [],
      date: '2026-08-27',
      pickupTime: '10:00',
      returnDate: '2026-08-30',
      returnTime: '18:00',
      passengers: 1,
      luggage: 3,
      specialRequirements: {
        childSeat: false,
        wheelchairAccessible: false,
        meetAndGreet: false,
      },
      vehicleType: 'estate' as VehicleType,
      distanceMiles: 86.2,
      estimatedDuration: 120,
      price: 95.0,
      discount: 9.5,
      tax: 17.1,
      total: 102.6,
      currency: 'GBP',
      paymentStatus: 'completed' as PaymentStatus,
      bookingStatus: BookingStatus.Confirmed,
      createdAt: '2026-08-22T09:15:00Z',
      updatedAt: '2026-08-22T09:15:00Z',
    },
    {
      bookingNumber: 'UKTB-2026-000004',
      passengerId: 'pass-004',
      operatorId: 'op-001',
      driverId: '',
      vehicleId: '',
      tripType: 'one_way' as TripType,
      pickup: demoLocations[10],
      destination: demoLocations[1],
      viaStops: [],
      date: '2026-08-28',
      pickupTime: '15:30',
      passengers: 5,
      luggage: 6,
      specialRequirements: {
        childSeat: true,
        wheelchairAccessible: false,
        meetAndGreet: false,
        notes: 'Two child seats required for ages 2 and 5',
      },
      vehicleType: 'minibus' as VehicleType,
      distanceMiles: 12.1,
      estimatedDuration: 35,
      price: 38.0,
      discount: 0,
      tax: 7.6,
      total: 45.6,
      currency: 'GBP',
      paymentStatus: 'pending' as PaymentStatus,
      bookingStatus: BookingStatus.PendingPayment,
      createdAt: '2026-08-25T10:00:00Z',
      updatedAt: '2026-08-25T10:00:00Z',
    },
    {
      bookingNumber: 'UKTB-2026-000005',
      passengerId: 'pass-005',
      operatorId: 'op-003',
      driverId: 'drv-005',
      vehicleId: 'veh-005',
      tripType: 'one_way' as TripType,
      pickup: demoLocations[4],
      destination: demoLocations[8],
      viaStops: [],
      date: '2026-08-25',
      pickupTime: '09:00',
      passengers: 1,
      luggage: 1,
      specialRequirements: {
        childSeat: false,
        wheelchairAccessible: true,
        meetAndGreet: false,
      },
      vehicleType: 'wheelchair_accessible' as VehicleType,
      distanceMiles: 420.0,
      estimatedDuration: 390,
      price: 380.0,
      discount: 38.0,
      tax: 68.4,
      total: 410.4,
      currency: 'GBP',
      paymentStatus: 'completed' as PaymentStatus,
      bookingStatus: BookingStatus.TripStarted,
      createdAt: '2026-08-23T11:30:00Z',
      updatedAt: '2026-08-25T09:05:00Z',
    },
    {
      bookingNumber: 'UKTB-2026-000006',
      passengerId: 'pass-001',
      operatorId: 'op-001',
      driverId: '',
      vehicleId: '',
      tripType: 'one_way' as TripType,
      pickup: demoLocations[11],
      destination: demoLocations[0],
      viaStops: [],
      date: '2026-08-25',
      pickupTime: '18:30',
      passengers: 1,
      luggage: 0,
      specialRequirements: {
        childSeat: false,
        wheelchairAccessible: false,
        meetAndGreet: false,
      },
      vehicleType: 'saloon' as VehicleType,
      distanceMiles: 3.1,
      estimatedDuration: 18,
      price: 11.5,
      discount: 0,
      tax: 2.3,
      total: 13.8,
      currency: 'GBP',
      paymentStatus: 'failed' as PaymentStatus,
      bookingStatus: BookingStatus.PaymentFailed,
      createdAt: '2026-08-25T12:00:00Z',
      updatedAt: '2026-08-25T12:01:00Z',
    },
    {
      id: 'bk-cash-001',
      bookingNumber: 'UKTB-2026-000008',
      passengerId: 'pax-001',
      operatorId: 'op-001',
      driverId: '',
      vehicleId: '',
      tripType: 'one_way' as TripType,
      pickup: {
        lat: 51.5074,
        lng: -0.1278,
        formattedAddress: '10 Downing Street, London SW1A 2AA',
        postcode: 'SW1A 2AA',
        placeId: 'demo-place-id-11',
      },
      destination: {
        lat: 51.4700,
        lng: -0.4543,
        formattedAddress: 'Heathrow Airport Terminal 5, London TW6 2GA',
        postcode: 'TW6 2GA',
        placeId: 'demo-place-id-12',
      },
      viaStops: [],
      date: '2026-08-30',
      pickupTime: '06:30',
      passengers: 2,
      luggage: 3,
      vehicleType: 'saloon' as VehicleType,
      distanceMiles: 18.4,
      estimatedDuration: 52,
      price: 52.0,
      discount: 0,
      tax: 10.4,
      total: 62.4,
      currency: 'GBP',
      paymentStatus: 'pending' as PaymentStatus,
      paymentMethod: 'cash',
      bookingStatus: BookingStatus.CashPendingApproval,
      createdAt: '2026-08-26T08:15:00Z',
      updatedAt: '2026-08-26T08:15:00Z',
    },
  ] as Booking[],

  quotes: [
    {
      id: 'qt-001',
      bookingId: 'UKTB-2026-000004',
      operatorId: 'op-001',
      operatorName: 'Kingsley Travel',
      operatorLogo: '/logos/kingsley-travel.png',
      vehicleType: 'minibus' as VehicleType,
      vehicleDescription: 'Volkswagen Caravelle Minibus - 7 Seats',
      vehicleImage: '/vehicles/vw-caravelle.jpg',
      passengerCapacity: 7,
      luggageCapacity: 6,
      rating: 4.8,
      totalReviews: 3245,
      estimatedJourneyTime: 35,
      isElectric: false,
      isHybrid: false,
      price: 45.6,
      discountPercent: 0,
      paymentTypes: ['card', 'cash'],
      features: ['Free waiting time', 'Meet and greet available', 'Flight tracking'],
      isLowestPrice: true,
    },
    {
      id: 'qt-002',
      bookingId: 'UKTB-2026-000004',
      operatorId: 'op-002',
      operatorName: 'Northern Taxi Services',
      operatorLogo: '/logos/northern-taxi.png',
      vehicleType: 'mpv' as VehicleType,
      vehicleDescription: 'Ford Galaxy MPV - 6 Seats',
      vehicleImage: '/vehicles/ford-galaxy.jpg',
      passengerCapacity: 6,
      luggageCapacity: 5,
      rating: 4.6,
      totalReviews: 1890,
      estimatedJourneyTime: 40,
      isElectric: false,
      isHybrid: true,
      price: 48.2,
      originalPrice: 52.0,
      discountPercent: 7,
      paymentTypes: ['card', 'cash'],
      features: ['Free waiting time', 'Hybrid vehicle'],
      isLowestPrice: false,
    },
    {
      id: 'qt-003',
      bookingId: 'UKTB-2026-000004',
      operatorId: 'op-003',
      operatorName: 'Capital Taxis Edinburgh',
      operatorLogo: '/logos/capital-taxis.png',
      vehicleType: 'minibus' as VehicleType,
      vehicleDescription: 'Mercedes Vito Minibus - 8 Seats',
      vehicleImage: '/vehicles/mercedes-vito.jpg',
      passengerCapacity: 8,
      luggageCapacity: 7,
      rating: 4.7,
      totalReviews: 987,
      estimatedJourneyTime: 32,
      isElectric: false,
      isHybrid: false,
      price: 51.0,
      paymentTypes: ['card', 'cash', 'apple_pay'],
      features: ['Free waiting time', 'Meet and greet', 'Large luggage space'],
      isLowestPrice: false,
    },
  ] as Quote[],

  reviews: [
    {
      id: 'rev-001',
      bookingId: 'UKTB-2026-000001',
      passengerId: 'pass-001',
      driverId: 'drv-001',
      operatorId: 'op-001',
      rating: 5,
      comment: 'Absolutely brilliant service. Mohammed was on time, the car was spotless, and he helped with my bags all the way to the terminal. Will definitely book again!',
      createdAt: '2026-08-26T08:00:00Z',
      isApproved: true,
    },
    {
      id: 'rev-002',
      bookingId: 'UKTB-2026-000003',
      passengerId: 'pass-003',
      driverId: 'drv-003',
      operatorId: 'op-002',
      rating: 4,
      comment: 'Good trip to Manchester Airport. Driver was friendly and knew the route well. Journey was comfortable.',
      createdAt: '2026-08-20T12:30:00Z',
      isApproved: true,
    },
    {
      id: 'rev-003',
      bookingId: 'UKTB-2026-000005',
      passengerId: 'pass-005',
      driverId: 'drv-005',
      operatorId: 'op-003',
      rating: 5,
      comment: 'Linda was incredible on the Edinburgh to Bristol journey. Very patient, made sure my wheelchair was secure, and stopped when I needed a break. Outstanding.',
      createdAt: '2026-08-24T15:00:00Z',
      isApproved: true,
    },
    {
      id: 'rev-004',
      bookingId: 'UKTB-2026-000001',
      passengerId: 'pass-002',
      driverId: 'drv-002',
      operatorId: 'op-001',
      rating: 5,
      comment: 'Sarah was absolutely fantastic. Professional, courteous, and the Mercedes was beautifully clean. Highly recommend.',
      createdAt: '2026-08-18T16:45:00Z',
      isApproved: true,
    },
    {
      id: 'rev-005',
      bookingId: 'UKTB-2026-000002',
      passengerId: 'pass-004',
      driverId: 'drv-004',
      operatorId: 'op-002',
      rating: 4,
      comment: 'Reliable service for our family trip. The MPV had plenty of room for the kids and luggage. Minor delay due to traffic but overall happy.',
      createdAt: '2026-08-15T13:20:00Z',
      isApproved: true,
    },
  ] as Review[],

  pricingRules: [
    {
      id: 'pr-001',
      operatorId: 'op-001',
      vehicleType: 'saloon' as VehicleType,
      baseFare: 3.0,
      perMile: 1.6,
      perMinute: 0.25,
      minimumFare: 5.0,
      bookingFee: 1.0,
      airportFee: 5.0,
      nightSurchargePercent: 20,
      weekendSurchargePercent: 10,
      peakTimeSurchargePercent: 25,
      congestionCharge: 15.0,
    },
    {
      id: 'pr-002',
      operatorId: 'op-001',
      vehicleType: 'executive' as VehicleType,
      baseFare: 5.0,
      perMile: 2.2,
      perMinute: 0.35,
      minimumFare: 8.0,
      bookingFee: 1.5,
      airportFee: 5.0,
      nightSurchargePercent: 20,
      weekendSurchargePercent: 15,
      peakTimeSurchargePercent: 25,
      congestionCharge: 15.0,
    },
    {
      id: 'pr-003',
      operatorId: 'op-001',
      vehicleType: 'electric' as VehicleType,
      baseFare: 2.5,
      perMile: 1.4,
      perMinute: 0.2,
      minimumFare: 4.5,
      bookingFee: 1.0,
      airportFee: 5.0,
      nightSurchargePercent: 15,
      weekendSurchargePercent: 10,
      peakTimeSurchargePercent: 20,
      congestionCharge: 0,
    },
    {
      id: 'pr-004',
      operatorId: 'op-002',
      vehicleType: 'saloon' as VehicleType,
      baseFare: 3.5,
      perMile: 1.8,
      perMinute: 0.3,
      minimumFare: 5.0,
      bookingFee: 1.5,
      airportFee: 7.5,
      nightSurchargePercent: 25,
      weekendSurchargePercent: 10,
      peakTimeSurchargePercent: 20,
      congestionCharge: 0,
    },
    {
      id: 'pr-005',
      operatorId: 'op-002',
      vehicleType: 'mpv' as VehicleType,
      baseFare: 4.5,
      perMile: 2.0,
      perMinute: 0.35,
      minimumFare: 7.0,
      bookingFee: 2.0,
      airportFee: 10.0,
      nightSurchargePercent: 20,
      weekendSurchargePercent: 15,
      peakTimeSurchargePercent: 25,
      congestionCharge: 0,
    },
    {
      id: 'pr-006',
      operatorId: 'op-002',
      vehicleType: 'estate' as VehicleType,
      baseFare: 3.5,
      perMile: 1.8,
      perMinute: 0.3,
      minimumFare: 5.5,
      bookingFee: 1.5,
      airportFee: 7.5,
      nightSurchargePercent: 20,
      weekendSurchargePercent: 10,
      peakTimeSurchargePercent: 20,
      congestionCharge: 0,
    },
    {
      id: 'pr-007',
      operatorId: 'op-003',
      vehicleType: 'saloon' as VehicleType,
      baseFare: 3.0,
      perMile: 1.5,
      perMinute: 0.25,
      minimumFare: 4.5,
      bookingFee: 1.0,
      airportFee: 5.0,
      nightSurchargePercent: 15,
      weekendSurchargePercent: 10,
      peakTimeSurchargePercent: 20,
      congestionCharge: 0,
    },
    {
      id: 'pr-008',
      operatorId: 'op-003',
      vehicleType: 'wheelchair_accessible' as VehicleType,
      baseFare: 3.0,
      perMile: 1.5,
      perMinute: 0.25,
      minimumFare: 4.5,
      bookingFee: 0,
      airportFee: 5.0,
      nightSurchargePercent: 15,
      weekendSurchargePercent: 5,
      peakTimeSurchargePercent: 15,
      congestionCharge: 0,
    },
    {
      id: 'pr-009',
      operatorId: 'op-001',
      vehicleType: 'mpv' as VehicleType,
      baseFare: 4.0,
      perMile: 2.0,
      perMinute: 0.3,
      minimumFare: 6.0,
      bookingFee: 2.0,
      airportFee: 7.5,
      nightSurchargePercent: 20,
      weekendSurchargePercent: 15,
      peakTimeSurchargePercent: 25,
      congestionCharge: 15.0,
    },
    {
      id: 'pr-010',
      operatorId: 'op-001',
      vehicleType: 'minibus' as VehicleType,
      baseFare: 5.0,
      perMile: 2.5,
      perMinute: 0.4,
      minimumFare: 8.0,
      bookingFee: 2.5,
      airportFee: 10.0,
      nightSurchargePercent: 20,
      weekendSurchargePercent: 15,
      peakTimeSurchargePercent: 25,
      congestionCharge: 15.0,
    },
    {
      id: 'pr-011',
      operatorId: 'op-001',
      vehicleType: 'wheelchair_accessible' as VehicleType,
      baseFare: 3.0,
      perMile: 1.5,
      perMinute: 0.25,
      minimumFare: 4.5,
      bookingFee: 0,
      airportFee: 5.0,
      nightSurchargePercent: 15,
      weekendSurchargePercent: 5,
      peakTimeSurchargePercent: 15,
      congestionCharge: 15.0,
    },
    {
      id: 'pr-012',
      operatorId: 'op-001',
      vehicleType: 'estate' as VehicleType,
      baseFare: 3.5,
      perMile: 1.8,
      perMinute: 0.3,
      minimumFare: 5.5,
      bookingFee: 1.5,
      airportFee: 5.0,
      nightSurchargePercent: 20,
      weekendSurchargePercent: 10,
      peakTimeSurchargePercent: 25,
      congestionCharge: 15.0,
    },
  ] as PricingRule[],

  airports: UK_AIRPORTS,

  locations: demoLocations,

  dashboardStats: {
    todayBookings: 147,
    todayRevenue: 8234.5,
    activeTrips: 23,
    availableDrivers: 89,
    onlineDrivers: 112,
    totalPassengers: 15420,
    totalOperators: 34,
    pendingApprovals: 5,
    pendingDocuments: 12,
    cancelledTrips: 3,
  },
};
